def ask(prompt):
    return prompt

summaryTxt = "your job is to anysize and summaryize legel documents that will be sent to you, you may resive partial documents, like a page from the midel of a contract, but you have to summaryze and anylise it to the best of your ablility, the summary must contain number of partys involved, time period of the document if any, important points and any othere important information that will be usefull to the user and give it in a proper formating and keep the answer small. \n This is the File- /n  - "

Data = '''
"Article-3:- Formation of new States and alteration of areas, boundaries or\nnames of existing States.—Parliament may by law—\n(a) form a new State by separation of territory from any State or\nby uniting two or more States or parts of States or by uniting any\nterritory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\n[Provided that no Bill for the purpose shall be introduced in either\nHouse of Parliament except on the recommendation of the President and unless,\nwhere the proposal contained in the Bill affects the area, boundaries or name of\nany of the States 2 ***, the Bill has been referred by the President to the\nLegislature of that State for expressing its views thereon within such period as\nmay be specified in the reference or within such further period as the President\nmay allow and the period so specified or allowed has expired.]\n[Explanation I.—In this article, in clauses (a) to (e), “State” includes a\nUnion territory, but in the proviso, “State” does not include a Union territory.\nExplanation II.—The power conferred on Parliament by clause (a)\nincludes the power to form a new State or Union territory by uniting a part of\nany State or Union territory to any other State or Union territory.]\n"
Article-3:- Formation of new States and alteration of areas, boundaries or\nnames of existing States.—Parliament may by law—\n(a) form a new State by separation of territory from any State or\nby uniting two or more States or parts of States or by uniting any\nterritory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\n[Provided that no Bill for the purpose shall be introduced in either\nHouse of Parliament except on the recommendation of the President and unless,\nwhere the proposal contained in the Bill affects the area, boundaries or name of\nany of the States 2 ***, the Bill has been referred by the President to the\nLegislature of that State for expressing its views thereon within such period as\nmay be specified in the reference or within such further period as the President\nmay allow and the period so specified or allowed has expired.]\n[Explanation I.—In this article, in clauses (a) to (e), “State” includes a\nUnion territory, but in the proviso, “State” does not include a Union territory.\nExplanation II.—The power conferred on Parliament by clause (a)\nincludes the power to form a new State or Union territory by uniting a part of\nany State or Union territory to any other State or Union territory.]\n"
Article-3:- Formation of new States and alteration of areas, boundaries or\nnames of existing States.—Parliament may by law—\n(a) form a new State by separation of territory from any State or\nby uniting two or more States or parts of States or by uniting any\nterritory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\n[Provided that no Bill for the purpose shall be introduced in either\nHouse of Parliament except on the recommendation of the President and unless,\nwhere the proposal contained in the Bill affects the area, boundaries or name of\nany of the States 2 ***, the Bill has been referred by the President to the\nLegislature of that State for expressing its views thereon within such period as\nmay be specified in the reference or within such further period as the President\nmay allow and the period so specified or allowed has expired.]\n[Explanation I.—In this article, in clauses (a) to (e), “State” includes a\nUnion territory, but in the proviso, “State” does not include a Union territory.\nExplanation II.—The power conferred on Parliament by clause (a)\nincludes the power to form a new State or Union territory by uniting a part of\nany State or Union territory to any other State or Union territory.]\n"
Article-3:- Formation of new States and alteration of areas, boundaries or\nnames of existing States.—Parliament may by law—\n(a) form a new State by separation of territory from any State or\nby uniting two or more States or parts of States or by uniting any\nterritory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\n[Provided that no Bill for the purpose shall be introduced in either\nHouse of Parliament except on the recommendation of the President and unless,\nwhere the proposal contained in the Bill affects the area, boundaries or name of\nany of the States 2 ***, the Bill has been referred by the President to the\nLegislature of that State for expressing its views thereon within such period as\nmay be specified in the reference or within such further period as the President\nmay allow and the period so specified or allowed has expired.]\n[Explanation I.—In this article, in clauses (a) to (e), “State” includes a\nUnion territory, but in the proviso, “State” does not include a Union territory.\nExplanation II.—The power conferred on Parliament by clause (a)\nincludes the power to form a new State or Union territory by uniting a part of\nany State or Union territory to any other State or Union territory.]\n"
Article-3:- Formation of new States and alteration of areas, boundaries or\nnames of existing States.—Parliament may by law—\n(a) form a new State by separation of territory from any State or\nby uniting two or more States or parts of States or by uniting any\nterritory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\n[Provided that no Bill for the purpose shall be introduced in either\nHouse of Parliament except on the recommendation of the President and unless,\nwhere the proposal contained in the Bill affects the area, boundaries or name of\nany of the States 2 ***, the Bill has been referred by the President to the\nLegislature of that State for expressing its views thereon within such period as\nmay be specified in the reference or within such further period as the President\nmay allow and the period so specified or allowed has expired.]\n[Explanation I.—In this article, in clauses (a) to (e), “State” includes a\nUnion territory, but in the proviso, “State” does not include a Union territory.\nExplanation II.—The power conferred on Parliament by clause (a)\nincludes the power to form a new State or Union territory by uniting a part of\nany State or Union territory to any other State or Union territory.]\n"
Article-3:- Formation of new States and alteration of areas, boundaries or\nnames of existing States.—Parliament may by law—\n(a) form a new State by separation of territory from any State or\nby uniting two or more States or parts of States or by uniting any\nterritory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\n[Provided that no Bill for the purpose shall be introduced in either\nHouse of Parliament except on the recommendation of the President and unless,\nwhere the proposal contained in the Bill affects the area, boundaries or name of\nany of the States 2 ***, the Bill has been referred by the President to the\nLegislature of that State for expressing its views thereon within such period as\nmay be specified in the reference or within such further period as the President\nmay allow and the period so specified or allowed has expired.]\n[Explanation I.—In this article, in clauses (a) to (e), “State” includes a\nUnion territory, but in the proviso, “State” does not include a Union territory.\nExplanation II.—The power conferred on Parliament by clause (a)\nincludes the power to form a new State or Union territory by uniting a part of\nany State or Union territory to any other State or Union territory.]\n"
Article-3:- Formation of new States and alteration of areas, boundaries or\nnames of existing States.—Parliament may by law—\n(a) form a new State by separation of territory from any State or\nby uniting two or more States or parts of States or by uniting any\nterritory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\n[Provided that no Bill for the purpose shall be introduced in either\nHouse of Parliament except on the recommendation of the President and unless,\nwhere the proposal contained in the Bill affects the area, boundaries or name of\nany of the States 2 ***, the Bill has been referred by the President to the\nLegislature of that State for expressing its views thereon within such period as\nmay be specified in the reference or within such further period as the President\nmay allow and the period so specified or allowed has expired.]\n[Explanation I.—In this article, in clauses (a) to (e), “State” includes a\nUnion territory, but in the proviso, “State” does not include a Union territory.\nExplanation II.—The power conferred on Parliament by clause (a)\nincludes the power to form a new State or Union territory by uniting a part of\nany State or Union territory to any other State or Union territory.]\n"
Article-3:- Formation of new States and alteration of areas, boundaries or\nnames of existing States.—Parliament may by law—\n(a) form a new State by separation of territory from any State or\nby uniting two or more States or parts of States or by uniting any\nterritory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\n[Provided that no Bill for the purpose shall be introduced in either\nHouse of Parliament except on the recommendation of the President and unless,\nwhere the proposal contained in the Bill affects the area, boundaries or name of\nany of the States 2 ***, the Bill has been referred by the President to the\nLegislature of that State for expressing its views thereon within such period as\nmay be specified in the reference or within such further period as the President\nmay allow and the period so specified or allowed has expired.]\n[Explanation I.—In this article, in clauses (a) to (e), “State” includes a\nUnion territory, but in the proviso, “State” does not include a Union territory.\nExplanation II.—The power conferred on Parliament by clause (a)\nincludes the power to form a new State or Union territory by uniting a part of\nany State or Union territory to any other State or Union territory.]\n"
Article-3:- Formation of new States and alteration of areas, boundaries or\nnames of existing States.—Parliament may by law—\n(a) form a new State by separation of territory from any State or\nby uniting two or more States or parts of States or by uniting any\nterritory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\n[Provided that no Bill for the purpose shall be introduced in either\nHouse of Parliament except on the recommendation of the President and unless,\nwhere the proposal contained in the Bill affects the area, boundaries or name of\nany of the States 2 ***, the Bill has been referred by the President to the\nLegislature of that State for expressing its views thereon within such period as\nmay be specified in the reference or within such further period as the President\nmay allow and the period so specified or allowed has expired.]\n[Explanation I.—In this article, in clauses (a) to (e), “State” includes a\nUnion territory, but in the proviso, “State” does not include a Union territory.\nExplanation II.—The power conferred on Parliament by clause (a)\nincludes the power to form a new State or Union territory by uniting a part of\nany State or Union territory to any other State or Union territory.]\n"
Article-3:- Formation of new States and alteration of areas, boundaries or\nnames of existing States.—Parliament may by law—\n(a) form a new State by separation of territory from any State or\nby uniting two or more States or parts of States or by uniting any\nterritory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\n[Provided that no Bill for the purpose shall be introduced in either\nHouse of Parliament except on the recommendation of the President and unless,\nwhere the proposal contained in the Bill affects the area, boundaries or name of\nany of the States 2 ***, the Bill has been referred by the President to the\nLegislature of that State for expressing its views thereon within such period as\nmay be specified in the reference or within such further period as the President\nmay allow and the period so specified or allowed has expired.]\n[Explanation I.—In this article, in clauses (a) to (e), “State” includes a\nUnion territory, but in the proviso, “State” does not include a Union territory.\nExplanation II.—The power conferred on Parliament by clause (a)\nincludes the power to form a new State or Union territory by uniting a part of\nany State or Union territory to any other State or Union territory.]\n"
Article-3:- Formation of new States and alteration of areas, boundaries or\nnames of existing States.—Parliament may by law—\n(a) form a new State by separation of territory from any State or\nby uniting two or more States or parts of States or by uniting any\nterritory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\n[Provided that no Bill for the purpose shall be introduced in either\nHouse of Parliament except on the recommendation of the President and unless,\nwhere the proposal contained in the Bill affects the area, boundaries or name of\nany of the States 2 ***, the Bill has been referred by the President to the\nLegislature of that State for expressing its views thereon within such period as\nmay be specified in the reference or within such further period as the President\nmay allow and the period so specified or allowed has expired.]\n[Explanation I.—In this article, in clauses (a) to (e), “State” includes a\nUnion territory, but in the proviso, “State” does not include a Union territory.\nExplanation II.—The power conferred on Parliament by clause (a)\nincludes the power to form a new State or Union territory by uniting a part of\nany State or Union territory to any other State or Union territory.]\n"
Article-3:- Formation of new States and alteration of areas, boundaries or\nnames of existing States.—Parliament may by law—\n(a) form a new State by separation of territory from any State or\nby uniting two or more States or parts of States or by uniting any\nterritory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\n[Provided that no Bill for the purpose shall be introduced in either\nHouse of Parliament except on the recommendation of the President and unless,\nwhere the proposal contained in the Bill affects the area, boundaries or name of\nany of the States 2 ***, the Bill has been referred by the President to the\nLegislature of that State for expressing its views thereon within such period as\nmay be specified in the reference or within such further period as the President\nmay allow and the period so specified or allowed has expired.]\n[Explanation I.—In this article, in clauses (a) to (e), “State” includes a\nUnion territory, but in the proviso, “State” does not include a Union territory.\nExplanation II.—The power conferred on Parliament by clause (a)\nincludes the power to form a new State or Union territory by uniting a part of\nany State or Union territory to any other State or Union territory.]\n"

'''

def summary(text):
    Output = ""
    L = len(text)
    again = 0
    a = 0
    data = ''
    while L:
        data += text[a]
        L -= 1
        a += 1
        
        if a > 1000:
            again = 1
            a == 0
            ans = ask(summaryTxt+data)
            Output = ", \n" + ans
            data = ""

    if a!= 0:
        ans = ask(summaryTxt+data)
        Output = ", \n Next \n" + ans
    return Output, again

summaryOf = "you will be given a list of anylizes and summary of different pages of legal documents, they were taken in seprate instances, so they may lake context, there can be summary of a single page out of context but you have to summarize that with propar formating"

def SummaryOfsum(text):
    ans = ask(summaryOf + text)
    return ans

info, again = summary(Data)
d = info

if again:
    info = SummaryOfsum(d)

print(info)



    
        
